language: java
android:
  components:
    # Update Android SDK Tools
    - tools

    - build-tools-23.0.1
    - android-23

    # Support library
    - extra-android-support
    - extra-android-m2repository
    
before_script: cd backend
script:
  - chmod +x ./gradle build
